-- Phase 1 / task 1.3: end users, sessions, AI insights, review workflow, erasure.
-- Telemetry-derived rows (end_user, user_session, ...) are never soft-deleted: they expire by
-- retention or are hard-deleted by erasure, which cascades to dependent rows.
-- Events live in ClickHouse; nothing here references them (ADR-0002).

-- F2: identified or anonymous visitor of a site.
CREATE TABLE end_user (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id        uuid        NOT NULL REFERENCES tenant (id),
    site_id          uuid        NOT NULL REFERENCES site (id),
    external_user_id text,                       -- null until identify()
    anonymous_id     text        NOT NULL,
    traits           jsonb       NOT NULL DEFAULT '{}',  -- redacted server-side
    first_seen_at    timestamptz NOT NULL DEFAULT now(),
    last_seen_at     timestamptz NOT NULL DEFAULT now(),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    version          bigint      NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX end_user_site_external_uq ON end_user (site_id, external_user_id)
    WHERE external_user_id IS NOT NULL;
CREATE INDEX end_user_site_anonymous_idx ON end_user (site_id, anonymous_id);

CREATE TABLE user_session (
    id               uuid        PRIMARY KEY,    -- generated by the SDK
    tenant_id        uuid        NOT NULL REFERENCES tenant (id),
    site_id          uuid        NOT NULL REFERENCES site (id),
    end_user_id      uuid        REFERENCES end_user (id) ON DELETE CASCADE,
    anonymous_id     text        NOT NULL,
    started_at       timestamptz NOT NULL,
    last_active_at   timestamptz NOT NULL,
    ended_at         timestamptz,
    duration_ms      bigint      NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    page_count       integer     NOT NULL DEFAULT 0 CHECK (page_count >= 0),
    platform         text,
    browser          text,
    entry_url        text,
    friction_score   smallint    CHECK (friction_score BETWEEN 0 AND 100),
    rage_click_count integer     NOT NULL DEFAULT 0,
    dead_click_count integer     NOT NULL DEFAULT 0,
    error_count      integer     NOT NULL DEFAULT 0,
    analysis_status  text        NOT NULL DEFAULT 'PENDING' CHECK (analysis_status IN (
                         'PENDING', 'PROCESSING', 'AI_ANALYZED', 'REVIEW_REQUIRED',
                         'HUMAN_APPROVED', 'HUMAN_REJECTED', 'FAILED')),
    assigned_to      uuid        REFERENCES app_user (id),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    version          bigint      NOT NULL DEFAULT 0
);
-- F3 session list filters
CREATE INDEX user_session_tenant_started_idx  ON user_session (tenant_id, started_at DESC);
CREATE INDEX user_session_tenant_friction_idx ON user_session (tenant_id, friction_score DESC);
CREATE INDEX user_session_tenant_status_idx   ON user_session (tenant_id, analysis_status);
CREATE INDEX user_session_end_user_idx        ON user_session (end_user_id);
-- identify(): link earlier anonymous sessions of the same visitor
CREATE INDEX user_session_site_anonymous_idx  ON user_session (site_id, anonymous_id);

-- F6. Hibernate pooled optimizer (allocationSize = 50) owns id generation: no column default,
-- so non-JPA inserts cannot collide with a pre-allocated block.
CREATE SEQUENCE session_insight_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE session_insight (
    id             bigint      PRIMARY KEY,
    tenant_id      uuid        NOT NULL REFERENCES tenant (id),
    session_id     uuid        NOT NULL REFERENCES user_session (id) ON DELETE CASCADE,
    summary        text,
    probable_cause text,
    friction_score smallint    CHECK (friction_score BETWEEN 0 AND 100),
    auto_tags      text[]      NOT NULL DEFAULT '{}',
    human_notes    text,
    evidence       jsonb       NOT NULL DEFAULT '[]',  -- replay timestamps the summary refers to
    embedding      vector(768),                        -- nomic-embed-text (ADR-0005)
    model_provider text,
    model_name     text,
    guardrail_rule text,                               -- rule that forced REVIEW_REQUIRED, if any
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    version        bigint      NOT NULL DEFAULT 0
);
CREATE INDEX session_insight_session_idx ON session_insight (session_id);
CREATE INDEX session_insight_embedding_hnsw ON session_insight USING hnsw (embedding vector_cosine_ops);

-- F7: append-only audit of review actions (the app role gets no UPDATE/DELETE, see V3).
CREATE TABLE review_event (
    id          bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_id   uuid        NOT NULL REFERENCES tenant (id),
    session_id  uuid        NOT NULL REFERENCES user_session (id) ON DELETE CASCADE,
    actor_id    uuid        REFERENCES app_user (id),  -- null for system transitions
    action      text        NOT NULL,
    from_status text,
    to_status   text,
    note        text,
    before      jsonb,
    after       jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX review_event_session_idx ON review_event (session_id, created_at);

-- F8: right-to-erasure workflow; progress tracks each store (postgres, clickhouse, s3).
CREATE TABLE erasure_request (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid        NOT NULL REFERENCES tenant (id),
    subject_type text        NOT NULL CHECK (subject_type IN ('END_USER', 'SESSION')),
    subject_id   uuid        NOT NULL,             -- no FK: the subject is what gets deleted
    status       text        NOT NULL DEFAULT 'REQUESTED'
                             CHECK (status IN ('REQUESTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED')),
    progress     jsonb       NOT NULL DEFAULT '{}',
    requested_by uuid        REFERENCES app_user (id),
    requested_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    version      bigint      NOT NULL DEFAULT 0
);
CREATE INDEX erasure_request_tenant_status_idx ON erasure_request (tenant_id, status);

-- v2 hook for F9 (ticketing): table only, no code until its phase.
CREATE TABLE external_ticket_link (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   uuid        NOT NULL REFERENCES tenant (id),
    session_id  uuid        NOT NULL REFERENCES user_session (id) ON DELETE CASCADE,
    system      text        NOT NULL CHECK (system IN ('JIRA', 'SERVICENOW', 'WEBHOOK')),
    external_id text        NOT NULL,
    url         text,
    created_by  uuid        REFERENCES app_user (id),
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX external_ticket_link_session_idx ON external_ticket_link (session_id);
